using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using VideoStore.Context;
using VideoStore.Models;

namespace VideoStore.migration
{
    public class DataSeeder 
    {

       public void insertCustomer(VideoStorContext context)
        {
            context.Customers.Add(new CustomerModel() { Id = 1, Name = "Nicholas Borders", Email = "nicholas_borders@hotmail.com", PhoneNumber = "0889521121", SwedishPersonalNumber = "198801121001" });
            context.Customers.Add(new CustomerModel() { Id = 2, Name = "Larue Cassese", Email = "larue_cassese@hotmail.com", PhoneNumber = "0889521122", SwedishPersonalNumber = "198801121551" });
            context.Customers.Add(new CustomerModel() { Id = 3, Name = "Queenie Charette", Email = "queenie_charette@hotmail.com", PhoneNumber = "0889521123", SwedishPersonalNumber = "198801121002" });
            context.Customers.Add(new CustomerModel() { Id = 4, Name = "Judie Michels", Email = "judie_michels@hotmail.com", PhoneNumber = "0889521124", SwedishPersonalNumber = "198801121003" });
            context.Customers.Add(new CustomerModel() { Id = 5, Name = "Marlyn Elsberry", Email = "marlyn_elsberry@hotmail.com", PhoneNumber = "0889521125", SwedishPersonalNumber = "198801121004" });
            context.Customers.Add(new CustomerModel() { Id = 6, Name = "Allen Lebel", Email = "allen_lebel@hotmail.com", PhoneNumber = "0889521126", SwedishPersonalNumber = "198801121005" });
            context.Customers.Add(new CustomerModel() { Id = 7, Name = "Camellia Landau", Email = "camellia_landau@hotmail.com", PhoneNumber = "0889521127", SwedishPersonalNumber = "198801121006" });
            context.Customers.Add(new CustomerModel() { Id = 8, Name = "Nia Calero", Email = "nia_calero@hotmail.com", PhoneNumber = "0889521128", SwedishPersonalNumber = "198801121007" });
            context.Customers.Add(new CustomerModel() { Id = 9, Name = "Bryce Baysinger", Email = "bryce_baysinger@hotmail.com", PhoneNumber = "0889521129", SwedishPersonalNumber = "198801121008" });
            context.Customers.Add(new CustomerModel() { Id = 10, Name = "Roseanne Ritz", Email = "roseanne_ritz@hotmail.com", PhoneNumber = "0889521130", SwedishPersonalNumber = "198801121009" });
            context.Customers.Add(new CustomerModel() { Id = 11, Name = "Will Lipford", Email = "will_lipford@hotmail.com", PhoneNumber = "0889521131", SwedishPersonalNumber = "198801121010" });
            context.Customers.Add(new CustomerModel() { Id = 12, Name = "Lula Pricer", Email = "lula_pricer@hotmail.com", PhoneNumber = "0889521132", SwedishPersonalNumber = "198801121011" });
            context.Customers.Add(new CustomerModel() { Id = 13, Name = "Nannette Quam", Email = "nannette_quam@hotmail.com", PhoneNumber = "0889521133", SwedishPersonalNumber = "198801121012" });
            context.Customers.Add(new CustomerModel() { Id = 14, Name = "Mica Halter", Email = "mica_halter@hotmail.com", PhoneNumber = "0889521134", SwedishPersonalNumber = "198801121013" });
            context.Customers.Add(new CustomerModel() { Id = 15, Name = "Despina Guerette", Email = "despina_guerette@hotmail.com", PhoneNumber = "0889521135", SwedishPersonalNumber = "198801121014" });
            context.Customers.Add(new CustomerModel() { Id = 16, Name = "Daphne Rudie", Email = "daphne_rudie@hotmail.com", PhoneNumber = "0889521136", SwedishPersonalNumber = "198801121015" });
            context.Customers.Add(new CustomerModel() { Id = 17, Name = "Ingrid Dalal", Email = "ingrid_dalal@hotmail.com", PhoneNumber = "0889521137", SwedishPersonalNumber = "198801121016" });
            context.Customers.Add(new CustomerModel() { Id = 18, Name = "Kristyn Gabriel", Email = "kristyn_gabriel@hotmail.com", PhoneNumber = "0889521138", SwedishPersonalNumber = "198801121017" });
            context.Customers.Add(new CustomerModel() { Id = 19, Name = "Daine Butter", Email = "daine_butter@hotmail.com", PhoneNumber = "0889521139", SwedishPersonalNumber = "198801121018" });
            context.Customers.Add(new CustomerModel() { Id = 20, Name = "Judy Bank", Email = "judy_bank@hotmail.com", PhoneNumber = "0889521140", SwedishPersonalNumber = "198801121019" });
            context.Customers.Add(new CustomerModel() { Id = 21, Name = "Michelina Trickey", Email = "michelina_trickey@hotmail.com", PhoneNumber = "0889521141", SwedishPersonalNumber = "198801121020" });
            context.Customers.Add(new CustomerModel() { Id = 22, Name = "Shellie Murr", Email = "shellie_murr@hotmail.com", PhoneNumber = "0889521142", SwedishPersonalNumber = "198801121021" });
            context.Customers.Add(new CustomerModel() { Id = 23, Name = "Helga Barrentine", Email = "helga_barrentine@hotmail.com", PhoneNumber = "0889521143", SwedishPersonalNumber = "198801121022" });
            context.Customers.Add(new CustomerModel() { Id = 24, Name = "Elayne Andress", Email = "elayne_andress@hotmail.com", PhoneNumber = "0889521144", SwedishPersonalNumber = "198801121023" });
            context.Customers.Add(new CustomerModel() { Id = 25, Name = "Lyndsey Pavone", Email = "lyndsey_pavone@hotmail.com", PhoneNumber = "0889521145", SwedishPersonalNumber = "198801121024" });
            context.Customers.Add(new CustomerModel() { Id = 26, Name = "Samantha Despres", Email = "samantha_despres@hotmail.com", PhoneNumber = "0889521146", SwedishPersonalNumber = "198801121025" });
            context.Customers.Add(new CustomerModel() { Id = 27, Name = "Marsha Legere", Email = "marsha_legere@hotmail.com", PhoneNumber = "0889521147", SwedishPersonalNumber = "198801121026" });
            context.Customers.Add(new CustomerModel() { Id = 28, Name = "Marissa Emmons", Email = "marissa_emmons@hotmail.com", PhoneNumber = "0889521148", SwedishPersonalNumber = "198801121027" });
            context.Customers.Add(new CustomerModel() { Id = 29, Name = "Gretta Simonsen", Email = "gretta_simonsen@hotmail.com", PhoneNumber = "0889521149", SwedishPersonalNumber = "198801121028" });
            context.Customers.Add(new CustomerModel() { Id = 30, Name = "Dominique Greggs", Email = "dominique_greggs@hotmail.com", PhoneNumber = "0889521150", SwedishPersonalNumber = "198801121029" });
            context.Customers.Add(new CustomerModel() { Id = 31, Name = "Lu Halliday", Email = "lu_halliday@hotmail.com", PhoneNumber = "0889521151", SwedishPersonalNumber = "198801121030" });
            context.Customers.Add(new CustomerModel() { Id = 32, Name = "Brooks Mikkelson", Email = "brooks_mikkelson@hotmail.com", PhoneNumber = "0889521152", SwedishPersonalNumber = "198801121031" });
            context.Customers.Add(new CustomerModel() { Id = 33, Name = "Hilda Heindel", Email = "hilda_heindel@hotmail.com", PhoneNumber = "0889521153", SwedishPersonalNumber = "198801121032" });
            context.Customers.Add(new CustomerModel() { Id = 34, Name = "Hallie Bergstrom", Email = "hallie_bergstrom@hotmail.com", PhoneNumber = "0889521154", SwedishPersonalNumber = "198801121033" });
            context.Customers.Add(new CustomerModel() { Id = 35, Name = "Derek Willoughby", Email = "derek_willoughby@hotmail.com", PhoneNumber = "0889521155", SwedishPersonalNumber = "198801121034" });
            context.Customers.Add(new CustomerModel() { Id = 36, Name = "Fran Essary", Email = "fran_essary@hotmail.com", PhoneNumber = "0889521156", SwedishPersonalNumber = "198801121035" });
            context.Customers.Add(new CustomerModel() { Id = 37, Name = "Janet Coonrod", Email = "janet_coonrod@hotmail.com", PhoneNumber = "0889521157", SwedishPersonalNumber = "198801121036" });
            context.Customers.Add(new CustomerModel() { Id = 38, Name = "Marian People", Email = "marian_people@hotmail.com", PhoneNumber = "0889521158", SwedishPersonalNumber = "198801121037" });
            context.Customers.Add(new CustomerModel() { Id = 39, Name = "Pearlene Bill", Email = "pearlene_bill@hotmail.com", PhoneNumber = "0889521159", SwedishPersonalNumber = "198801121038" });
            context.Customers.Add(new CustomerModel() { Id = 40, Name = "Jewel Pointer", Email = "jewel_pointer@hotmail.com", PhoneNumber = "0889521160", SwedishPersonalNumber = "198801121039" });
            context.Customers.Add(new CustomerModel() { Id = 41, Name = "Isabella Shead", Email = "isabella_shead@hotmail.com", PhoneNumber = "0889521161", SwedishPersonalNumber = "198801121040" });
            context.Customers.Add(new CustomerModel() { Id = 42, Name = "Loren Touchet", Email = "loren_touchet@hotmail.com", PhoneNumber = "0889521162", SwedishPersonalNumber = "198801121041" });
            context.Customers.Add(new CustomerModel() { Id = 43, Name = "Arnetta Millender", Email = "arnetta_millender@hotmail.com", PhoneNumber = "0889521163", SwedishPersonalNumber = "198801121042" });
            context.Customers.Add(new CustomerModel() { Id = 44, Name = "Maragaret Settle", Email = "maragaret_settle@hotmail.com", PhoneNumber = "0889521164", SwedishPersonalNumber = "198801121043" });
            context.Customers.Add(new CustomerModel() { Id = 45, Name = "Min Schiffer", Email = "min_schiffer@hotmail.com", PhoneNumber = "0889521165", SwedishPersonalNumber = "198801121044" });
            context.Customers.Add(new CustomerModel() { Id = 46, Name = "Harley Cass", Email = "harley_cass@hotmail.com", PhoneNumber = "0889521166", SwedishPersonalNumber = "198801121045" });
            context.Customers.Add(new CustomerModel() { Id = 47, Name = "Lorine Tober", Email = "lorine_tober@hotmail.com", PhoneNumber = "0889521167", SwedishPersonalNumber = "198801121046" });
            context.Customers.Add(new CustomerModel() { Id = 48, Name = "Augusta Kozlowski", Email = "augusta_kozlowski@hotmail.com", PhoneNumber = "0889521168", SwedishPersonalNumber = "198801121047" });
            context.Customers.Add(new CustomerModel() { Id = 49, Name = "Charlette Nish", Email = "charlette_nish@hotmail.com", PhoneNumber = "0889521169", SwedishPersonalNumber = "198801121048" });
            context.Customers.Add(new CustomerModel() { Id = 50, Name = "Demetrius Macarthur", Email = "demetrius_macarthur@hotmail.com", PhoneNumber = "0889521170", SwedishPersonalNumber = "198801121049" });

            context.SaveChanges();       
            
            
        }

        public void insertMovieRents(VideoStorContext context)
        {
            context.MovieRents.Add(new MovieRentModel() { Id = 1, CustomerId = 2, MovieId = 1, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 2, CustomerId = 44, MovieId = 4, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 3, CustomerId = 32, MovieId = 6, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 4, CustomerId = 15, MovieId = 2, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 5, CustomerId = 5, MovieId = 10, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 6, CustomerId = 12, MovieId = 120, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 7, CustomerId = 3, MovieId = 88, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 8, CustomerId = 20, MovieId = 99, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 9, CustomerId = 42, MovieId = 180, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 10, CustomerId = 17, MovieId = 200, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 11, CustomerId = 19, MovieId = 17, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 12, CustomerId = 13, MovieId = 36, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 13, CustomerId = 7, MovieId = 77, RentStartDateTime = DateTime.Today.AddDays(-3), ReturnDateTime = DateTime.Today.AddDays(-1), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 14, CustomerId = 1, MovieId = 190, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 15, CustomerId = 3, MovieId = 14, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });

            
            context.MovieRents.Add( new MovieRentModel() { Id = 16, CustomerId = 3, MovieId = 88, RentStartDateTime = DateTime.Today.AddDays(-3), ReturnDateTime =DateTime.Today.AddDays(-2), IsReturned=true });
            context.MovieRents.Add(new MovieRentModel() { Id = 17, CustomerId = 4, MovieId = 12, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned=false });
            context.MovieRents.Add(new MovieRentModel() { Id = 18, CustomerId = 5, MovieId = 20, RentStartDateTime = new DateTime(2017, 12, 8), ReturnDateTime = new DateTime(2017, 12, 10), IsReturned = true });
            context.MovieRents.Add(new MovieRentModel() { Id = 19, CustomerId = 1, MovieId = 130, RentStartDateTime = new DateTime(2017, 12, 3), ReturnDateTime = new DateTime(2017, 12, 5), IsReturned = true });
            context.MovieRents.Add(new MovieRentModel() { Id = 20, CustomerId = 1, MovieId = 5, RentStartDateTime = new DateTime(2017, 12, 3), ReturnDateTime = new DateTime(2017, 12, 5), IsReturned = true });
            context.MovieRents.Add(new MovieRentModel() { Id = 21, CustomerId = 8, MovieId = 115, RentStartDateTime = new DateTime(2017, 12, 3), ReturnDateTime = new DateTime(2017, 12, 6), IsReturned = true });
            context.MovieRents.Add(new MovieRentModel() { Id = 22, CustomerId = 3, MovieId = 5, RentStartDateTime = new DateTime(2017, 12, 3), ReturnDateTime = new DateTime(2017, 12, 5), IsReturned = true });
            context.MovieRents.Add(new MovieRentModel() { Id = 23, CustomerId = 12, MovieId = 5, RentStartDateTime = new DateTime(2017, 12, 3), ReturnDateTime = new DateTime(2017, 12, 5), IsReturned = true });
            context.MovieRents.Add(new MovieRentModel() { Id = 24, CustomerId = 4, MovieId = 8, RentStartDateTime = new DateTime(2017, 12, 3), ReturnDateTime = new DateTime(2017, 12, 5), IsReturned = true });
            context.MovieRents.Add(new MovieRentModel() { Id = 25, CustomerId = 27, MovieId = 88, RentStartDateTime = new DateTime(2017, 12, 3), ReturnDateTime = new DateTime(2017, 12, 5), IsReturned = true });
            context.MovieRents.Add(new MovieRentModel() { Id = 26, CustomerId = 33, MovieId = 103, RentStartDateTime = new DateTime(2017, 12, 3), ReturnDateTime = new DateTime(2017, 12, 5), IsReturned = true });
            context.MovieRents.Add(new MovieRentModel() { Id = 27, CustomerId = 44, MovieId = 190, RentStartDateTime = new DateTime(2017, 12, 12), ReturnDateTime = new DateTime(2017, 12, 14), IsReturned = true });

            context.MovieRents.Add(new MovieRentModel() { Id = 28, CustomerId = 42, MovieId = 1, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 29, CustomerId = 17, MovieId = 7, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 30, CustomerId = 19, MovieId = 240, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 31, CustomerId = 13, MovieId = 240, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 32, CustomerId = 7, MovieId = 192, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 33, CustomerId = 1, MovieId = 192, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id =34, CustomerId = 3, MovieId = 92, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });

            context.MovieRents.Add(new MovieRentModel() { Id = 28, CustomerId = 42, MovieId = 1, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 29, CustomerId = 17, MovieId = 7, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 30, CustomerId = 43, MovieId = 240, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 31, CustomerId = 25, MovieId = 50, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 32, CustomerId = 9, MovieId = 220, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 33, CustomerId = 38, MovieId = 192, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });
            context.MovieRents.Add(new MovieRentModel() { Id = 34, CustomerId = 48, MovieId = 88, RentStartDateTime = DateTime.Today, ReturnDateTime = DateTime.Today.AddDays(2), IsReturned = false });

            context.SaveChanges();
       
        }
             

        public void insertMovies(VideoStorContext context)
        {
           
            context.Movies.Add(new MovieModel() { Id = 1,Title="The Shawshank Redemption (1994)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 2,Title="The Godfather (1972)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 3,Title="The Godfather: Part II (1974)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 4,Title="Pulp Fiction (1994)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 5,Title="The Good, the Bad and the Ugly (1966)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 6,Title="The Dark Knight (2008)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 7,Title="12 Angry Men (1957)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 8,Title="Schindler's List (1993)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 9,Title="The Lord of the Rings: The Return of the King (2003)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 10,Title="Fight Club (1999)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 11,Title="Star Wars: Episode V - The Empire Strikes Back (1980)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 12,Title="The Lord of the Rings: The Fellowship of the Ring (2001)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 13,Title="One Flew Over the Cuckoo's Nest (1975)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 14,Title="Goodfellas (1990)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 15,Title="Seven Samurai (1954)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 16,Title="Inception (2010)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 17,Title="Star Wars (1977)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 18,Title="Forrest Gump (1994)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 19,Title="The Matrix (1999)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 20,Title="The Lord of the Rings: The Two Towers (2002)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 21,Title="City of God (2002)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 22,Title="The Silence of the Lambs (1991)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 23,Title="Se7en (1995)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 24,Title="Once Upon a Time in the West (1968)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 25,Title="Casablanca (1942)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 26,Title="The Usual Suspects (1995)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 27,Title="Raiders of the Lost Ark (1981)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 28,Title="Rear Window (1954)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 29,Title="It's a Wonderful Life (1946)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 30,Title="Psycho (1960)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 31,Title="Léon: The Professional (1994)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 32,Title="Sunset Blvd. (1950)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 33,Title="American History X (1998)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 34,Title="Apocalypse Now (1979)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 35,Title="Terminator 2: Judgment Day (1991)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 36,Title="Memento (2000)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 37,Title="Saving Private Ryan (1998)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 38,Title="City Lights (1931)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 39,Title="Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 40,Title="Alien (1979)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 41,Title="Modern Times (1936)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 42,Title="Spirited Away (2001)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 43,Title="Gravity (2013)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 44,Title="North by Northwest (1959)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 45,Title="Back to the Future (1985)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 46,Title="Citizen Kane (1941)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 47,Title="The Pianist (2002)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 48,Title="M (1931)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 49,Title="Life Is Beautiful (1997)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 50,Title="The Shining (1980)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 51,Title="The Departed (2006)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 52,Title="Paths of Glory (1957)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 53,Title="Vertigo (1958)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 54,Title="American Beauty (1999)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 55,Title="Django Unchained (2012)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 56,Title="Double Indemnity (1944)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 57,Title="Taxi Driver (1976)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 58,Title="The Dark Knight Rises (2012)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 59,Title="Aliens (1986)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 60,Title="The Green Mile (1999)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 61,Title="The Intouchables (2011)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 62,Title="Gladiator (2000)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 63,Title="WALL·E (2008)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 64,Title="The Lives of Others (2006)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 65,Title="Toy Story 3 (2010)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 66,Title="The Great Dictator (1940)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 67,Title="A Clockwork Orange (1971)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 68,Title="The Prestige (2006)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 69,Title="Amélie (2001)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 70,Title="Lawrence of Arabia (1962)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 71,Title="To Kill a Mockingbird (1962)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 72,Title="Reservoir Dogs (1992)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 73,Title="Das Boot (1981)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 74,Title="Cinema Paradiso (1988)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 75,Title="The Lion King (1994)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 76,Title="The Treasure of the Sierra Madre (1948)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 77,Title="The Third Man (1949)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 78,Title="Once Upon a Time in America (1984)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 79,Title="Requiem for a Dream (2000)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 80,Title="Star Wars: Episode VI - Return of the Jedi (1983)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 81,Title="Eternal Sunshine of the Spotless Mind (2004)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 82,Title="Full Metal Jacket (1987)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 83,Title="Braveheart (1995)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 84,Title="L.A. Confidential (1997)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 85,Title="Oldboy (2003)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 86,Title="Singin' in the Rain (1952)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 87,Title="Metropolis (1927)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 88,Title="Chinatown (1974)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 89,Title="Rashomon (1950)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 90,Title="Some Like It Hot (1959)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 91,Title="Bicycle Thieves (1948)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 92,Title="All About Eve (1950)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 93,Title="Monty Python and the Holy Grail (1975)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 94,Title="Princess Mononoke (1997)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 95,Title="Amadeus (1984)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 96,Title="2001: A Space Odyssey (1968)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 97,Title="Witness for the Prosecution (1957)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 98,Title="The Apartment (1960)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 99,Title="The Sting (1973)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 100,Title="Unforgiven (1992)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 101,Title="Grave of the Fireflies (1988)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 102,Title="Indiana Jones and the Last Crusade (1989)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 103,Title="Raging Bull (1980)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 104,Title="The Bridge on the River Kwai (1957)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 105,Title="Die Hard (1988)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 106,Title="Yojimbo (1961)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 107,Title="Batman Begins (2005)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 108,Title="A Separation (2011)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 109,Title="Inglourious Basterds (2009)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 110,Title="For a Few Dollars More (1965)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 111,Title="Mr. Smith Goes to Washington (1939)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 112,Title="Snatch. (2000)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 113,Title="Toy Story (1995)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 114,Title="On the Waterfront (1954)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 115,Title="The Great Escape (1963)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 116,Title="Downfall (2004)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 117,Title="Pan's Labyrinth (2006)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 118,Title="Up (2009)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 119,Title="The General (1926)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 120,Title="The Seventh Seal (1957)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 121,Title="Heat (1995)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 122,Title="The Elephant Man (1980)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 123,Title="The Maltese Falcon (1941)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 124,Title="The Kid (1921)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 125,Title="Blade Runner (1982)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 126,Title="Wild Strawberries (1957)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 127,Title="Rebecca (1940)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 128,Title="Scarface (1983)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 129,Title="Ikiru (1952)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 130,Title="Ran (1985)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 131,Title="Fargo (1996)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 132,Title="Gran Torino (2008)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 133,Title="Touch of Evil (1958)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 134,Title="The Big Lebowski (1998)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 135,Title="The Gold Rush (1925)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 136,Title="The Deer Hunter (1978)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 137,Title="Cool Hand Luke (1967)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 138,Title="It Happened One Night (1934)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 139,Title="Diabolique (1955)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 140,Title="No Country for Old Men (2007)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 141,Title="The Sixth Sense (1999)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 142,Title="Lock, Stock and Two Smoking Barrels (1998)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 143,Title="Jaws (1975)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 144,Title="Good Will Hunting (1997)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 145,Title="Strangers on a Train (1951)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 146,Title="Casino (1995)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 147,Title="Judgment at Nuremberg (1961)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 148,Title="The Grapes of Wrath (1940)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 149,Title="The Wizard of Oz (1939)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 150,Title="Platoon (1986)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 151,Title="Sin City (2005)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 152,Title="Butch Cassidy and the Sundance Kid (1969)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 153,Title="Kill Bill: Vol. 1 (2003)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 154,Title="The Thing (1982)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 155,Title="Trainspotting (1996)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 156,Title="Gone with the Wind (1939)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 157,Title="High Noon (1952)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 158,Title="Annie Hall (1977)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 159,Title="Hotel Rwanda (2004)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 160,Title="The Hunt (2012)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 161,Title="Warrior (2011)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 162,Title="The Secret in Their Eyes (2009)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 163,Title="Finding Nemo (2003)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 164,Title="My Neighbor Totoro (1988)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 165,Title="V for Vendetta (2005)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 166,Title="Notorious (1946)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 167,Title="Dial M for Murder (1954)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 168,Title="The Avengers (2012)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 169,Title="How to Train Your Dragon (2010)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 170,Title="Life of Brian (1979)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 171,Title="Into the Wild (2007)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 172,Title="The Best Years of Our Lives (1946)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 173,Title="Network (1976)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 174,Title="The Terminator (1984)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 175,Title="Million Dollar Baby (2004)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 176,Title="There Will Be Blood (2007)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 177,Title="Ben-Hur (1959)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 178,Title="The Night of the Hunter (1955)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 179,Title="The Big Sleep (1946)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 180,Title="The King's Speech (2010)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 181,Title="Stand by Me (1986)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 182,Title="The 400 Blows (1959)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 183,Title="Twelve Monkeys (1995)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 184,Title="Groundhog Day (1993)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 185,Title="Donnie Darko (2001)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 186,Title="Dog Day Afternoon (1975)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 187,Title="Amores Perros (2000)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 188,Title="Howl's Moving Castle (2004)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 189,Title="Mary and Max (2009)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 190,Title="Gandhi (1982)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 191,Title="The Bourne Ultimatum (2007)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 192,Title="A Beautiful Mind (2001)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 193,Title="Persona (1966)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 194,Title="The Killing (1956)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 195,Title="The Graduate (1967)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 196,Title="Rush (2013)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 197,Title="Black Swan (2010)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 198,Title="The Princess Bride (1987)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 199,Title="Who's Afraid of Virginia Woolf? (1966)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 200,Title="The Hustler (1961)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 201,Title="The Man Who Shot Liberty Valance (1962)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 202,Title="La Strada (1954)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 203,Title="Anatomy of a Murder (1959)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 204,Title="8½ (1963)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 205,Title="The Manchurian Candidate (1962)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 206,Title="Rocky (1976)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 207,Title="The Exorcist (1973)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 208,Title="Slumdog Millionaire (2008)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 209,Title="In the Name of the Father (1993)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 210,Title="Stalag 17 (1953)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 211,Title="Rope (1948)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 212,Title="The Wild Bunch (1969)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 213,Title="Barry Lyndon (1975)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 214,Title="Monsters, Inc. (2001)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 215,Title="Fanny and Alexander (1982)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 216,Title="Infernal Affairs (2002)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 217,Title="The Truman Show (1998)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 218,Title="Roman Holiday (1953)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 219,Title="Life of Pi (2012)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 220,Title="Pirates of the Caribbean: The Curse of the Black Pearl (2003)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 221,Title="Memories of Murder (2003)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 222,Title="All Quiet on the Western Front (1930)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 223,Title="Harry Potter and the Deathly Hallows: Part 2 (2011)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 224,Title="Sleuth (1972)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 225,Title="Stalker (1979)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 226,Title="Jurassic Park (1993)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 227,Title="A Streetcar Named Desire (1951)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 228,Title="Star Trek (2009)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 229,Title="Ratatouille (2007)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 230,Title="Ip Man (2008)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 231,Title="A Fistful of Dollars (1964)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 232,Title="The Diving Bell and the Butterfly (2007)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 233,Title="The Hobbit: An Unexpected Journey (2012)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 234,Title="District 9 (2009)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 235,Title="Shutter Island (2010)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 236,Title="Rain Man (1988)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 237,Title="Incendies (2010)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 238,Title="Rosemary's Baby (1968)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 239,Title="La Haine (1995)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 240,Title="3 Idiots (2009)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 241,Title="The Artist (2011)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 242,Title="Nausicaä of the Valley of the Wind (1984)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 243,Title="Beauty and the Beast (1991)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 244,Title="Three Colors: Red (1994)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 245,Title="Bringing Up Baby (1938)", NumberOfCopies = 3, Genre="Drama", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 246,Title="Mystic River (2003)", NumberOfCopies = 3, Genre="Horror", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 247,Title="In the Heat of the Night (1967)", NumberOfCopies = 3, Genre="Romance", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 248,Title="Arsenic and Old Lace (1944)", NumberOfCopies = 3, Genre="Science fiction", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 249,Title="Before Sunrise (1995)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});
            context.Movies.Add(new MovieModel() { Id = 250,Title="Papillon (1973)", NumberOfCopies = 3, Genre="Action", MaxRentDays=2});

            context.SaveChanges();
        }

    }
}